on: [push]

jobs:
  test_packages_job:
    runs-on: ubuntu-latest
    name: A job to test created packages
    steps:
    - uses: actions/checkout@v2
    - name: Simulating Build
        # simulating a build 
        run: |
          wget https://github.com/newrelic/nri-apache/releases/download/v0.0.1/nri-apache-0.0.1-1.x86_64.rpm -O ./dist/nri-apache-0.0.1-1.x86_64.rpm
          wget https://github.com/newrelic/nri-apache/releases/download/v0.0.1/nri-apache_0.0.1-1_amd64.deb -O ./dist/nri-apache_0.0.1-1_amd64.deb

    - name: Test packages installation
      uses: paologallinaharbur/test-packages-action@v1.0.2
      with:
        TAG: '0.0.1'
        INTEGRATION: 'nri-apache'
        TEST_EXISTENCE: '/var/db/newrelic-infra/newrelic-integrations/bin/nri-apache /etc/newrelic-infra/integrations.d/apache-config.yml.sample /var/db/newrelic-infra/newrelic-integrations/apache-definition.yml'